# Generated by Django 4.1.5 on 2023-01-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
