# Generated by Django 4.1.5 on 2023-02-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
